function out = country2fetch

out =  {'Austria'
        'Bosnia and Herzegovina'
        'Belgium'
        'Bulgaria'
        'Switzerland'
        'Czech'
        'Germany'
        'Denmark'
        'Estonia'
        'Spain'
        'Finland'
        'France'
        'Greece'
        'Croatia'
        'Hungary'
        'Ireland'
        'Italy'
        'Lithuania'
        'Luxembourg'
        'Latvia'
        'Montenegro'
        'Netherlands'
        'Norway'
        'Poland'
        'Portugal'
        'Romania'
        'Serbia'
        'Sweden'
        'Slovenia'
        'Slovakia'
        'Russia'
        'United Kingdom'};