function out = countrycode(countryname)

countries = {   'Afghanistan'	'The Islamic Republic of Afghanistan'	'UN member state'	'AF'	'AFG' 'Kabul' '' ''
                'Åland Islands'	'Åland'	'Finland'	'AX'	'ALA' 'Helsinki' '' ''
                'Albania'	'The Republic of Albania'	'UN member state'	'AL'	'ALB' 'Tirana' '41.3281482000000' '19.8184435000000'
                'Algeria'	'The People Democratic Republic of Algeria'	'UN member state'	'DZ'	'DZA' 'Algiers' '' ''
                'American Samoa'	'The Territory of American Samoa'	'United States'	'AS'	'ASM' 'Apia' '' ''
                'Andorra'	'The Principality of Andorra'	'UN member state'	'AD'	'AND' 'Andorra la Vella' '' ''
                'Angola'	'The Republic of Angola'	'UN member state'	'AO'	'AGO' 'Luanda' '' ''
                'Anguilla'	'Anguilla'	'United Kingdom'	'AI'	'AIA' '' '' ''
                'Antarctica '	'All land and ice shelves south of the 60th parallel south'	'Antarctic Treaty'	'AQ'	'ATA' '' '' ''
                'Antigua and Barbuda'	'Antigua and Barbuda'	'UN member state'	'AG'	'ATG' 'Saint John' '' ''
                'Argentina'	'The Argentine Republic'	'UN member state'	'AR'	'ARG' 'Buenos Aires' '' ''
                'Armenia'	'The Republic of Armenia'	'UN member state'	'AM'	'ARM' 'Yerevan' '' ''
                'Aruba'	'Aruba'	'Netherlands'	'AW'	'ABW' '' '' ''
                'Australia '	'The Commonwealth of Australia'	'UN member state'	'AU'	'AUS' 'Canberra' '' ''
                'Austria'	'The Republic of Austria'	'UN member state'	'AT'	'AUT' 'Vienna' '48.2083537000000' '16.3725042000000'
                'Azerbaijan'	'The Republic of Azerbaijan'	'UN member state'	'AZ'	'AZE' 'Baku' '' ''
                'Bahamas (the)'	'The Commonwealth of The Bahamas'	'UN member state'	'BS'	'BHS' 'Nassau' '' ''
                'Bahrain'	'The Kingdom of Bahrain'	'UN member state'	'BH'	'BHR' 'Manama' '' ''
                'Bangladesh'	'The People Republic of Bangladesh'	'UN member state'	'BD'	'BGD' 'Dhaka'  '' ''
                'Barbados'	'Barbados'	'UN member state'	'BB'	'BRB' 'Bridgetown' '' ''
                'Belarus'	'The Republic of Belarus'	'UN member state'	'BY'	'BLR' 'Minsk'  '53.9024716000000' '27.5618225000000'
                'Belgium'	'The Kingdom of Belgium'	'UN member state'	'BE'	'BEL' 'Brussels' '50.8465573000000' '4.35169700000000'
                'Belize'	'Belize'	'UN member state'	'BZ'	'BLZ' 'Belmopan' '' ''
                'Benin'	'The Republic of Benin'	'UN member state'	'BJ'	'BEN' 'Porto-Novo' '' ''
                'Bermuda'	'Bermuda'	'United Kingdom'	'BM'	'BMU' '' '' ''
                'Bhutan'	'The Kingdom of Bhutan'	'UN member state'	'BT'	'BTN' 'Thimphu' '' ''
                'Bolivia (Plurinational State of)'	'The Plurinational State of Bolivia'	'UN member state'	'BO'	'BOL' 'La Paz' '' ''
                'Bonaire'	'Bonaire, Sint Eustatius and Saba'	'Netherlands'	'BQ'	'BES' '' '' ''
                'Bosnia and Herzegovina'	'Bosnia and Herzegovina'	'UN member state'	'BA'	'BIH' 'Sarajevo' '43.8519774000000' '18.3866868000000'
                'Botswana'	'The Republic of Botswana'	'UN member state'	'BW'	'BWA' 'Gaborone' '' ''
                'Bouvet Island'	'Bouvet Island'	'Norway'	'BV'	'BVT' '' '' ''
                'Brazil'	'The Federative Republic of Brazil'	'UN member state'	'BR'	'BRA' 'Brasilia' '' ''
                'British Indian Ocean Territory (the)'	'The British Indian Ocean Territory'	'United Kingdom'	'IO'	'IOT' '' '' ''
                'Brunei Darussalam '	'The Nation of Brunei, the Abode of Peace'	'UN member state'	'BN'	'BRN' 'Bandar Seri Begawan' '' ''
                'Bulgaria'	'The Republic of Bulgaria'	'UN member state'	'BG'	'BGR' 'Sofia' '42.6977028000000' '23.3217359000000'
                'Burkina Faso'	'Burkina Faso'	'UN member state'	'BF'	'BFA' 'Ouagadougou' '' ''
                'Burundi'	'The Republic of Burundi'	'UN member state'	'BI'	'BDI' 'Gitega' '' ''
                'Cabo Verde '	'The Republic of Cabo Verde'	'UN member state'	'CV'	'CPV' 'Praia' '' ''
                'Cambodia'	'The Kingdom of Cambodia'	'UN member state'	'KH'	'KHM' 'Phnom Penh' '' ''
                'Cameroon'	'The Republic of Cameroon'	'UN member state'	'CM'	'CMR' 'Yaounde' '' ''
                'Canada'	'Canada'	'UN member state'	'CA'	'CAN' 'Ottawa' '' ''
                'Cayman Islands (the)'	'The Cayman Islands'	'United Kingdom'	'KY'	'CYM' '' '' ''
                'Central African Republic (the)'	'The Central African Republic'	'UN member state'	'CF'	'CAF' 'Bangui' '' ''
                'Chad'	'The Republic of Chad'	'UN member state'	'TD'	'TCD' 'N''Djamena' '' ''
                'Chile'	'The Republic of Chile'	'UN member state'	'CL'	'CHL' 'Santiago' '' ''
                'China'	'The People Republic of China'	'UN member state'	'CN'	'CHN' 'Beijing' '' ''
                'Christmas Island'	'The Territory of Christmas Island'	'Australia'	'CX'	'CXR' '' '' ''
                'Cocos (Keeling) Islands (the)'	'The Territory of Cocos (Keeling) Islands'	'Australia'	'CC'	'CCK' '' '' ''
                'Colombia'	'The Republic of Colombia'	'UN member state'	'CO'	'COL' 'Bogotá' '' ''
                'Comoros (the)'	'The Union of the Comoros'	'UN member state'	'KM'	'COM' 'Moroni' '' ''
                'Congo (the Democratic Republic of the)'	'The Democratic Republic of the Congo'	'UN member state'	'CD'	'COD' 'Kinshasa' '' ''
                'Congo (the) '	'The Republic of the Congo'	'UN member state'	'CG'	'COG' 'Brazzaville' '' ''
                'Cook Islands (the)'	'The Cook Islands'	'New Zealand'	'CK'	'COK' '' '' ''
                'Costa Rica'	'The Republic of Costa Rica'	'UN member state'	'CR'	'CRI' 'San Jose' '' ''
                'Côte dIvoire '	'The Republic of Côte dIvoire'	'UN member state'	'CI'	'CIV' 'Yamoussoukro' '' ''
                'Croatia'	'The Republic of Croatia'	'UN member state'	'HR'	'HRV' 'Zagreb' '45.8131847000000' '15.9771774000000'
                'Cuba'	'The Republic of Cuba'	'UN member state'	'CU'	'CUB' 'Havana' '' ''
                'Curaçao'	'The Country of Curaçao'	'Netherlands'	'CW'	'CUW' '' '' ''
                'Cyprus'	'The Republic of Cyprus'	'UN member state'	'CY'	'CYP' 'Nicosia' '' ''
                'Czechia '	'The Czech Republic'	'UN member state'	'CZ'	'CZE' 'Prague' '50.0874654000000' '14.4212535000000'
                'Denmark'	'The Kingdom of Denmark'	'UN member state'	'DK'	'DNK' 'Copenhagen' '55.6867243000000' '12.5700724000000'
                'Djibouti'	'The Republic of Djibouti'	'UN member state'	'DJ'	'DJI' 'Djibouti' '' ''
                'Dominica'	'The Commonwealth of Dominica'	'UN member state'	'DM'	'DMA' 'Roseau' '' ''
                'Dominican Republic (the)'	'The Dominican Republic'	'UN member state'	'DO'	'DOM' 'Santo Domingo' '' ''
                'Ecuador'	'The Republic of Ecuador'	'UN member state'	'EC'	'ECU' 'Quito' '' ''
                'Egypt'	'The Arab Republic of Egypt'	'UN member state'	'EG'	'EGY' 'Cairo' '' ''
                'El Salvador'	'The Republic of El Salvador'	'UN member state'	'SV'	'SLV' 'San Salvador' '' ''
                'Equatorial Guinea'	'The Republic of Equatorial Guinea'	'UN member state'	'GQ'	'GNQ' 'Oyala ' '' ''
                'Eritrea'	'The State of Eritrea'	'UN member state'	'ER'	'ERI' 'Asmara' '' ''
                'Estonia'	'The Republic of Estonia'	'UN member state'	'EE'	'EST' 'Tallinn' '59.4372155000000' '24.7453688000000'
                'Eswatini '	'The Kingdom of Eswatini'	'UN member state'	'SZ'	'SWZ' 'Lobamba' '' ''
                'Ethiopia'	'The Federal Democratic Republic of Ethiopia'	'UN member state'	'ET'	'ETH' 'Addis Ababa' '' ''
                'Falkland Islands (the) [Malvinas] '	'The Falkland Islands'	'United Kingdom'	'FK'	'FLK' '' '' ''
                'Faroe Islands (the)'	'The Faroe Islands'	'Denmark'	'FO'	'FRO' '' '' ''
                'Fiji'	'The Republic of Fiji'	'UN member state'	'FJ'	'FJI' 'Suva' '' ''
                'Finland'	'The Republic of Finland'	'UN member state'	'FI'	'FIN' 'Helsinki' '60.1674881000000' '24.9427473000000'
                'France '	'The French Republic'	'UN member state'	'FR'	'FRA' 'Paris' '48.8588897000000' '2.32004102172008'
                'French Guiana'	'Guyane'	'France'	'GF'	'GUF' '' '' ''
                'French Polynesia'	'French Polynesia'	'France'	'PF'	'PYF' '' '' ''
                'French Southern Territories (the) [m]'	'The French Southern and Antarctic Lands'	'France'	'TF'	'ATF' '' '' ''
                'Gabon'	'The Gabonese Republic'	'UN member state'	'GA'	'GAB' 'Libreville' '' ''
                'Gambia (the)'	'The Republic of The Gambia'	'UN member state'	'GM'	'GMB' 'Banjul' '' ''
                'Georgia'	'Georgia'	'UN member state'	'GE'	'GEO' 'Tbilisi' '' ''
                'Germany'	'The Federal Republic of Germany'	'UN member state'	'DE'	'DEU' 'Berlin' '52.5170365000000' '13.3888599000000'
                'Ghana'	'The Republic of Ghana'	'UN member state'	'GH'	'GHA' 'Accra' '' ''
                'Gibraltar'	'Gibraltar'	'United Kingdom'	'GI'	'GIB' '' '' ''
                'Greece'	'The Hellenic Republic'	'UN member state'	'EL'	'GRC' 'Athens' '37.9839412000000' '23.7283052000000'
                'Greenland'	'Kalaallit Nunaat'	'Denmark'	'GL'	'GRL' '' '' ''
                'Grenada'	'Grenada'	'UN member state'	'GD'	'GRD' 'Saint George''s' '' ''
                'Guadeloupe'	'Guadeloupe'	'France'	'GP'	'GLP' '' '' ''
                'Guam'	'The Territory of Guam'	'United States'	'GU'	'GUM' '' '' ''
                'Guatemala'	'The Republic of Guatemala'	'UN member state'	'GT'	'GTM' 'Guatemala City' '' ''
                'Guernsey'	'The Bailiwick of Guernsey'	'British Crown'	'GG'	'GGY' '' '' ''
                'Guinea'	'The Republic of Guinea'	'UN member state'	'GN'	'GIN' 'Conakry' '' ''
                'Guinea-Bissau'	'The Republic of Guinea-Bissau'	'UN member state'	'GW'	'GNB' 'Bissau' '' ''
                'Guyana'	'The Co-operative Republic of Guyana'	'UN member state'	'GY'	'GUY' 'Georgetown' '' ''
                'Haiti'	'The Republic of Haiti'	'UN member state'	'HT'	'HTI' 'Port-au-Prince' '' ''
                'Heard Island and McDonald Islands'	'The Territory of Heard Island and McDonald Islands'	'Australia'	'HM'	'HMD' '' '' ''
                'Holy See (the) '	'The Holy See'	'UN observer state'	'VA'	'VAT' '' '' ''
                'Honduras'	'The Republic of Honduras'	'UN member state'	'HN'	'HND' 'Tegucigalpa' '' ''
                'Hong Kong'	'The Hong Kong Special Administrative Region of China[10]'	'China'	'HK'	'HKG' '' '' ''
                'Hungary'	'Hungary'	'UN member state'	'HU'	'HUN' 'Budapest' '47.4979937000000' '19.0403594000000'
                'Iceland'	'Iceland'	'UN member state'	'IS'	'ISL' 'Reykjavik' '' ''
                'India'	'The Republic of India'	'UN member state'	'IN'	'IND' 'New Delhi' '' ''
                'Indonesia'	'The Republic of Indonesia'	'UN member state'	'ID'	'IDN' 'Jakarta' '' ''
                'Iran (Islamic Republic of)'	'The Islamic Republic of Iran'	'UN member state'	'IR'	'IRN' 'Tehran' '' ''
                'Iraq'	'The Republic of Iraq'	'UN member state'	'IQ'	'IRQ' 'Baghdad' '' ''
                'Ireland'	'Ireland'	'UN member state'	'IE'	'IRL' 'Dublin' '53.3497645000000' '-6.26027320000000'
                'Isle of Man'	'The Isle of Man'	'British Crown'	'IM'	'IMN' '' '' ''
                'Israel'	'The State of Israel'	'UN member state'	'IL'	'ISR' 'Jerusalem' '' ''
                'Italy'	'The Italian Republic'	'UN member state'	'IT'	'ITA' 'Rome' '41.8933203000000' '12.4829321000000'
                'Jamaica'	'Jamaica'	'UN member state'	'JM'	'JAM' 'Kingston' '' ''
                'Japan'	'Japan'	'UN member state'	'JP'	'JPN' 'Tokyo' '' ''
                'Jersey'	'The Bailiwick of Jersey'	'British Crown'	'JE'	'JEY' '' '' ''
                'Jordan'	'The Hashemite Kingdom of Jordan'	'UN member state'	'JO'	'JOR' 'Amman' '' ''
                'Kazakhstan'	'The Republic of Kazakhstan'	'UN member state'	'KZ'	'KAZ' 'Nur-Sultan' '' ''
                'Kenya'	'The Republic of Kenya'	'UN member state'	'KE'	'KEN' 'Nairobi'  '' ''
                'Kiribati'	'The Republic of Kiribati'	'UN member state'	'KI'	'KIR' 'Tarawa' '' ''
                'Kosovo'	'Republic of Kosovo'	'UN member state'	'KX'	'KX' 'Pristina' '' ''
                'South Korea (the Democratic Peoples Republic of) '	'The Democratic Peoples Republic of Korea'	'UN member state'	'KP'	'PRK' 'Seoul' '' ''
                'North Korea (the Republic of)'	'The Republic of Korea'	'UN member state'	'KR'	'KOR' 'Pyongyang' '' ''
                'Kuwait'	'The State of Kuwait'	'UN member state'	'KW'	'KWT' 'Kuwait City' '' ''
                'Kyrgyzstan'	'The Kyrgyz Republic'	'UN member state'	'KG'	'KGZ' 'Bishkek' '' ''
                'Lao Peoples Democratic Republic (the) '	'The Lao Peoples Democratic Republic'	'UN member state'	'LA'	'LAO' 'Vientiane' '' ''
                'Latvia'	'The Republic of Latvia'	'UN member state'	'LV'	'LVA' 'Riga' '56.9493977000000' '24.1051846000000'
                'Lebanon'	'The Lebanese Republic'	'UN member state'	'LB'	'LBN' 'Beirut' '' ''
                'Lesotho'	'The Kingdom of Lesotho'	'UN member state'	'LS'	'LSO' 'Maseru' '' ''
                'Liberia'	'The Republic of Liberia'	'UN member state'	'LR'	'LBR' 'Monrovia' '' ''
                'Libya'	'The State of Libya'	'UN member state'	'LY'	'LBY' 'Tripoli' '' ''
                'Liechtenstein'	'The Principality of Liechtenstein'	'UN member state'	'LI'	'LIE' 'Vaduz' '' ''
                'Lithuania'	'The Republic of Lithuania'	'UN member state'	'LT'	'LTU' 'Vilnius' '54.6870458000000' '25.2829111000000'
                'Luxembourg'	'The Grand Duchy of Luxembourg'	'UN member state'	'LU'	'LUX' 'Luxembourg' '49.6112768000000' '6.12979900000000'
                'Macao '	'The Macao Special Administrative Region of China'	'China'	'MO'	'MAC' '' '' ''
                'North Macedonia '	'The Republic of North Macedonia'	'UN member state'	'MK'	'MKD' 'Skopje' '41.9960924000000' '21.4316495000000'
                'Madagascar'	'The Republic of Madagascar'	'UN member state'	'MG'	'MDG' 'Antananarivo' '' ''
                'Malawi'	'The Republic of Malawi'	'UN member state'	'MW'	'MWI' 'Lilongwe' '' ''
                'Malaysia'	'Malaysia'	'UN member state'	'MY'	'MYS' 'Kuala Lumpur' '' ''
                'Maldives'	'The Republic of Maldives'	'UN member state'	'MV'	'MDV' 'Male' '' ''
                'Mali'	'The Republic of Mali'	'UN member state'	'ML'	'MLI' 'Bamako' '' ''
                'Malta'	'The Republic of Malta'	'UN member state'	'MT'	'MLT' 'Valletta' '' ''
                'Marshall Islands (the)'	'The Republic of the Marshall Islands'	'UN member state'	'MH'	'MHL' 'Majuro' '' ''
                'Martinique'	'Martinique'	'France'	'MQ'	'MTQ' '' '' ''
                'Mauritania'	'The Islamic Republic of Mauritania'	'UN member state'	'MR'	'MRT' 'Nouakchott' '' ''
                'Mauritius'	'The Republic of Mauritius'	'UN member state'	'MU'	'MUS' 'Port Louis' '' ''
                'Mayotte'	'The Department of Mayotte'	'France'	'YT'	'MYT' '' '' ''
                'Mexico'	'The United Mexican States'	'UN member state'	'MX'	'MEX' 'Mexico City' '' ''
                'Micronesia (Federated States of)'	'The Federated States of Micronesia'	'UN member state'	'FM'	'FSM' 'Palikir' '' ''
                'Moldova (the Republic of)'	'The Republic of Moldova'	'UN member state'	'MD'	'MDA' 'Chisinau' '47.0273122000000' '28.8263397594133'
                'Monaco'	'The Principality of Monaco'	'UN member state'	'MC'	'MCO' 'Monaco' '' ''
                'Mongolia'	'Mongolia'	'UN member state'	'MN'	'MNG' 'Ulaanbaatar' '' ''
                'Montenegro'	'Montenegro'	'UN member state'	'ME'	'MNE' 'Podgorica' '42.4415238000000' '19.2621081000000'
                'Montserrat'	'Montserrat'	'United Kingdom'	'MS'	'MSR' '' '' ''
                'Morocco'	'The Kingdom of Morocco'	'UN member state'	'MA'	'MAR' 'Rabat' '' ''
                'Mozambique'	'The Republic of Mozambique'	'UN member state'	'MZ'	'MOZ' 'Maputo' '' ''
                'Myanmar [t]'	'The Republic of the Union of Myanmar'	'UN member state'	'MM'	'MMR' 'Naypyidaw' '' ''
                'Namibia'	'The Republic of Namibia'	'UN member state'	'NA'	'NAM' 'Windhoek' '' ''
                'Nauru'	'The Republic of Nauru'	'UN member state'	'NR'	'NRU' 'Yaren District' '' ''
                'Nepal'	'The Federal Democratic Republic of Nepal'	'UN member state'	'NP'	'NPL' 'Kathmandu' '' ''
                'Netherlands (the)'	'The Kingdom of the Netherlands'	'UN member state'	'NL'	'NLD' 'Amsterdam' '52.0990859500000' '4.29697969964969'
                'New Caledonia'	'New Caledonia'	'France'	'NC'	'NCL' '' '' ''
                'New Zealand'	'New Zealand'	'UN member state'	'NZ'	'NZL' 'Wellington' '' ''
                'Nicaragua'	'The Republic of Nicaragua'	'UN member state'	'NI'	'NIC' 'Managua' '' ''
                'Niger (the)'	'The Republic of the Niger'	'UN member state'	'NE'	'NER' 'Niamey' '' ''
                'Nigeria'	'The Federal Republic of Nigeria'	'UN member state'	'NG'	'NGA' 'Abuja' '' ''
                'Niue'	'Niue'	'New Zealand'	'NU'	'NIU'  '' '' ''
                'Norfolk Island'	'The Territory of Norfolk Island'	'Australia'	'NF'	'NFK' '' '' ''
                'Northern Mariana Islands (the)'	'The Commonwealth of the Northern Mariana Islands'	'United States'	'MP'	'MNP' '' '' ''
                'Norway'	'The Kingdom of Norway'	'UN member state'	'NO'	'NOR' 'Oslo' '59.9133301000000' '10.757933'
                'Oman'	'The Sultanate of Oman'	'UN member state'	'OM'	'OMN' 'Muscat' '' ''
                'Pakistan'	'The Islamic Republic of Pakistan'	'UN member state'	'PK'	'PAK' 'Islamabad' '' ''
                'Palau'	'The Republic of Palau'	'UN member state'	'PW'	'PLW' 'Ngerulmud' '' ''
                'Palestine, State of'	'The State of Palestine'	'UN observer state'	'PS'	'PSE' 'Jerusalem' '' ''
                'Panama'	'The Republic of Panamá'	'UN member state'	'PA'	'PAN' 'Panama City' '' ''
                'Papua New Guinea'	'The Independent State of Papua New Guinea'	'UN member state'	'PG'	'PNG' 'Port Moresby' '' ''
                'Paraguay'	'The Republic of Paraguay'	'UN member state'	'PY'	'PRY' 'Asunción' '' ''
                'Peru'	'The Republic of Perú'	'UN member state'	'PE'	'PER' 'Lima' '' ''
                'Philippines (the)'	'The Republic of the Philippines'	'UN member state'	'PH'	'PHL' 'Manila' '' ''
                'Pitcairn [u]'	'The Pitcairn, Henderson, Ducie and Oeno Islands'	'United Kingdom'	'PN'	'PCN' '' '' ''
                'Poland'	'The Republic of Poland'	'UN member state'	'PL'	'POL' 'Warsaw' '52.2319581000000' '21.0067249000000'
                'Portugal'	'The Portuguese Republic'	'UN member state'	'PT'	'PRT' 'Lisbon' '38.7077507000000' '-9.13659190000000'
                'Puerto Rico'	'The Commonwealth of Puerto Rico'	'United States'	'PR'	'PRI' '' '' ''
                'Qatar'	'The State of Qatar'	'UN member state'	'QA'	'QAT' 'Doha' '' ''
                'Réunion'	'Réunion'	'France'	'RE'	'REU' '' '' ''
                'Romania'	'Romania'	'UN member state'	'RO'	'ROU' 'Bucharest' '44.4361414000000' '26.1027202000000'
                'Russian Federation (the) '	'The Russian Federation'	'UN member state'	'RU'	'RUS' 'Moscow' '55.7504461000000' '37.6174943000000'
                'Rwanda'	'The Republic of Rwanda'	'UN member state'	'RW'	'RWA' 'Kigali' '' ''
                'Saint Barthélemy'	'The Collectivity of Saint-Barthélemy'	'France'	'BL'	'BLM' '' '' ''
                'Saint Helena'	'Saint Helena, Ascension and Tristan da Cunha'	'United Kingdom'	'SH'	'SHN' '' '' ''
                'Saint Kitts and Nevis'	'Saint Kitts and Nevis'	'UN member state'	'KN'	'KNA' 'Basseterre' '' ''
                'Saint Lucia'	'Saint Lucia'	'UN member state'	'LC'	'LCA' 'Castries' '' ''
                'Saint Martin (French part)'	'The Collectivity of Saint-Martin'	'France'	'MF'	'MAF' '' '' ''
                'Saint Pierre and Miquelon'	'The Overseas Collectivity of Saint-Pierre and Miquelon'	'France'	'PM'	'SPM' '' '' ''
                'Saint Vincent and the Grenadines'	'Saint Vincent and the Grenadines'	'UN member state'	'VC'	'VCT' 'Kingstown' '' ''
                'Samoa'	'The Independent State of Samoa'	'UN member state'	'WS'	'WSM' 'Apia' '' ''
                'San Marino'	'The Republic of San Marino'	'UN member state'	'SM'	'SMR' 'San Marino' '' ''
                'Sao Tome and Principe'	'The Democratic Republic of São Tomé and Príncipe'	'UN member state'	'ST'	'STP' 'São Tomé' '' ''
                'Saudi Arabia'	'The Kingdom of Saudi Arabia'	'UN member state'	'SA'	'SAU' 'Riyadh' '' ''
                'Senegal'	'The Republic of Senegal'	'UN member state'	'SN'	'SEN' 'Dakar' '' ''
                'Serbia'	'The Republic of Serbia'	'UN member state'	'RS'	'SRB' 'Belgrade' '44.8178131000000' '20.4568974000000'
                'Seychelles'	'The Republic of Seychelles'	'UN member state'	'SC'	'SYC' 'Victoria' '' ''
                'Sierra Leone'	'The Republic of Sierra Leone'	'UN member state'	'SL'	'SLE' 'Freetown' '' ''
                'Singapore'	'The Republic of Singapore'	'UN member state'	'SG'	'SGP' 'Singapore' '' ''
                'Sint Maarten (Dutch part)'	'Sint Maarten'	'Netherlands'	'SX'	'SXM' '' '' ''
                'Slovakia'	'The Slovak Republic'	'UN member state'	'SK'	'SVK' 'Bratislava' '48.1516988000000' '17.1093063000000'
                'Slovenia'	'The Republic of Slovenia'	'UN member state'	'SI'	'SVN' 'Ljubljana' '46.0500268000000' '14.5069289000000'
                'Solomon Islands'	'The Solomon Islands'	'UN member state'	'SB'	'SLB' 'Honiara' '' ''
                'Somalia'	'The Federal Republic of Somalia'	'UN member state'	'SO'	'SOM' 'Mogadishu' '' ''
                'South Africa'	'The Republic of South Africa'	'UN member state'	'ZA'	'ZAF' 'Pretoria' '' ''
                'South Georgia and the South Sandwich Islands'	'South Georgia and the South Sandwich Islands'	'United Kingdom'	'GS'	'SGS' '' '' ''
                'South Sudan'	'The Republic of South Sudan'	'UN member state'	'SS'	'SSD' 'Juba' '' ''
                'Spain'	'The Kingdom of Spain'	'UN member state'	'ES'	'ESP' 'Madrid' '40.4167047000000' '-3.70358250000000'
                'Sri Lanka'	'The Democratic Socialist Republic of Sri Lanka'	'UN member state'	'LK'	'LKA' 'Sri Jayawardenepura Kotte' '' ''
                'Sudan (the)'	'The Republic of the Sudan'	'UN member state'	'SD'	'SDN' 'Khartoum' '' ''
                'Suriname'	'The Republic of Suriname'	'UN member state'	'SR'	'SUR' 'Paramaribo' '' ''
                'Svalbard'	'Svalbard and Jan Mayen'	'Norway'	'SJ'	'SJM' '' '' ''
                'Sweden'	'The Kingdom of Sweden'	'UN member state'	'SE'	'SWE' 'Stockholm' '59.3251172000000' '18.0710935000000'
                'Switzerland'	'The Swiss Confederation'	'UN member state'	'CH'	'CHE' 'Bern' '46.9482713000000' '7.45145120000000'
                'Syrian Arab Republic (the) '	'The Syrian Arab Republic'	'UN member state'	'SY'	'SYR' 'Damascus' '' ''
                'Taiwan'	'The Republic of China'	'Disputed [z]'	'TW'	'TWN' 'Taipei' '' ''
                'Tajikistan'	'The Republic of Tajikistan'	'UN member state'	'TJ'	'TJK' 'Dushanbe' '' ''
                'Tanzania, the United Republic of'	'The United Republic of Tanzania'	'UN member state'	'TZ'	'TZA' 'Dodoma' '' ''
                'Thailand'	'The Kingdom of Thailand'	'UN member state'	'TH'	'THA' 'Bangkok' '' ''
                'Timor-Leste '	'The Democratic Republic of Timor-Leste'	'UN member state'	'TL'	'TLS' 'Dili' '' ''
                'Togo'	'The Togolese Republic'	'UN member state'	'TG'	'TGO' 'Lomé' '' ''
                'Tokelau'	'Tokelau'	'New Zealand'	'TK'	'TKL' '' '' ''
                'Tonga'	'The Kingdom of Tonga'	'UN member state'	'TO'	'TON' 'Nuku''alofa' '' ''
                'Trinidad and Tobago'	'The Republic of Trinidad and Tobago'	'UN member state'	'TT'	'TTO' 'Port of Spain' '' ''
                'Tunisia'	'The Republic of Tunisia'	'UN member state'	'TN'	'TUN' 'Tunis' '' ''
                'Turkey'	'The Republic of Turkey'	'UN member state'	'TR'	'TUR' 'Ankara' '39.9207886000000' '32.8540482000000'
                'Turkmenistan'	'Turkmenistan'	'UN member state'	'TM'	'TKM' 'Ashgabat' '' ''
                'Turks and Caicos Islands (the)'	'The Turks and Caicos Islands'	'United Kingdom'	'TC'	'TCA' '' '' ''
                'Tuvalu'	'Tuvalu'	'UN member state'	'TV'	'TUV' 'Funafuti' '' ''
                'Uganda'	'The Republic of Uganda'	'UN member state'	'UG'	'UGA' 'Kampala' '' ''
                'Ukraine'	'Ukraine'	'UN member state'	'UA'	'UKR' 'Kyiv' '50.4500336000000' '30.5241361000000'
                'United Arab Emirates (the)'	'The United Arab Emirates'	'UN member state'	'AE'	'ARE' 'Abu Dhabi' '' ''
                'United Kingdom'	'The United Kingdom of Great Britain and Northern Ireland'	'UN member state'	'GB'	'GBR' 'London' '51.5073219000000' '-0.127647400000000'
                'United States Minor Outlying Islands (the) '	'Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island'	'United States'	'UM'	'UMI' '' '' ''
                'United States of America (the)'	'The United States of America'	'UN member state'	'US'	'USA' 'Washington, D.C.' '' ''
                'Uruguay'	'The Oriental Republic of Uruguay'	'UN member state'	'UY'	'URY' 'Montevideo' '' ''
                'Uzbekistan'	'The Republic of Uzbekistan'	'UN member state'	'UZ'	'UZB' 'Tashkent' '' ''
                'Vanuatu'	'The Republic of Vanuatu'	'UN member state'	'VU'	'VUT' 'Port Vila' '' ''
                'Venezuela (Bolivarian Republic of)'	'The Bolivarian Republic of Venezuela'	'UN member state'	'VE'	'VEN' 'Caracas' '' ''
                'Vietnam'	'The Socialist Republic of Viet Nam'	'UN member state'	'VN'	'VNM' 'Hanoi' '' ''
                'Virgin Islands (British) '	'The Virgin Islands'	'United Kingdom'	'VG'	'VGB' '' '' ''
                'Virgin Islands (U.S.) '	'The Virgin Islands of the United States'	'United States'	'VI'	'VIR' '' '' ''
                'Wallis and Futuna'	'The Territory of the Wallis and Futuna Islands'	'France'	'WF'	'WLF' '' '' ''
                'Western Sahara '	'The Sahrawi Arab Democratic Republic'	'Disputed [ai]'	'EH'	'ESH' '' '' ''
                'Yemen'	'The Republic of Yemen'	'UN member state'	'YE'	'YEM' '	Sana''a' '' ''
                'Zambia'	'The Republic of Zambia'	'UN member state'	'ZM'	'ZMB' 'Lusaka' '' ''
                'Zimbabwe'	'The Republic of Zimbabwe'	'UN member state'	'ZW'	'ZWE' 'Harare' '' ''
                };

countries = cell2table(countries, 'VariableNames', {'countryname' 'officialname' 'sovereignty' 'alpha-2code' 'alpha-3code' 'capital' 'latitude' 'longitude'}) ;

if isa(countryname,'string') || isa(countryname,'char')
    if length(countryname) == 2
        out.countryname = countries.("countryname"){contains(countries.("alpha-2code"), countryname)} ;
        out.alpha3 = countries.("alpha-3code"){contains(countries.("alpha-2code"), countryname)} ;
        out.capital = countries.('capital'){contains(countries.("alpha-2code"), countryname)} ;
        out.latitude = countries.('latitude'){contains(countries.("alpha-2code"), countryname)} ;
        out.longitude = countries.('longitude'){contains(countries.("alpha-2code"), countryname)} ;
    else
        out.alpha2 = countries.("alpha-2code"){contains(countries.countryname, countryname)} ;
        out.alpha3 = countries.("alpha-3code"){contains(countries.countryname, countryname)} ;
        out.capital = countries.('capital'){contains(countries.countryname, countryname)} ;
    end
elseif isa(countryname,'cell')
    alpha2 = cellfun(@(x) countries.("alpha-2code")(contains(countries.countryname,x)),countryname,'UniformOutput',false);
    alpha3 = cellfun(@(x) countries.("alpha-3code")(contains(countries.countryname,x)),countryname,'UniformOutput',false);
    capital = cellfun(@(x) countries.("capital")(contains(countries.countryname,x)),countryname,'UniformOutput',false);
    merge = [alpha2 alpha3 capital] ;
    out = cell2table(merge,'VariableNames',{'alpha2' 'alpha3' 'capital'});
end

