function elecfuel = retrieveEUcap 

        elecfuel = {'RA110'	'hydro'
                    'RA110ROR'	'hydro_runof'
                    'RA120'	'hydro_reservoir'
                    'RA130'	'hydro_pumped'
                    'RA200'	'geothermal'
                    'RA300'	'wind'
                    'RA310'	'windon'
                    'RA320'	'windoff'
                    'RA400'	'solar'
                    'RA410'	'solar_thermal'
                    'RA420'	'solar_pv'                    
                    'RA500'	'marine'
                    'R5100'	'biomass'
                    'R5210P' 'other_biogas'
                    'R5220P' 'other_biogas'
                    'R5290'	'other_biogas'
                    'R5300'	'other_biogas'
                    'W6000'	'waste'
                    'CF'	'thermal'
                    'N9000'	'Nuclear fuels and other fuels n.e.c.'
                    'X9900'	'Other fuels n.e.c.'} ;