function elecfuel = retrieveEUprod 

        elecfuel = {'C0110'	'Anthracite' 'coal'
                    'C0121'	'Coking coal' 'coal'
                    'C0129'	'Other bituminous coal' 'coal'
                    'C0210'	'Sub-bituminous coal' 'coal'
                    'C0220'	'Lignite' 'coal'
                    'C0311'	'Coke oven coke' 'coal'
                    'C0312'	'Gas coke' 'coal'
                    'C0320'	'Patent fuel' 'coal'
                    'C0330'	'Brown coal briquettes' 'coal'
                    'C0340'	'Coal tar' 'coal'
                    'C0350'	'Coke oven gas' 'coal'
                    'C0360'	'Gas works gas' 'coal'
                    'C0371'	'Blast furnace gas' 'coal'
                    'C0379'	'Other recovered gases' 'coal'
                    'P1100'	'Peat' 'peat'
                    'P1200'	'Peat products' 'peat'
                    'S2000'	'Oil shale and oil sands' 'oil'
                    'G3000'	'Natural gas' 'gas'
                    'O4100_TOT'	'Crude oil' 'oil'
                    'O4200'	'Natural gas liquids' 'oil'
                    'O4610'	'Refinery gas' 'oil'
                    'O4630'	'Liquefied petroleum gases' 'oil'
                    'O4640'	'Naphtha' 'oil'
                    'O4661'	'Kerosene-type jet fuel' 'oil'
                    'O4669'	'Other kerosene' 'oil'
                    'O4671'	'Gas oil and diesel oil' 'oil'
                    'O4680'	'Fuel oil' 'oil'
                    'O4690'	'Other oil products' 'oil'
                    'O4694'	'Petroleum coke' 'oil'
                    'O4695'	'Bitumen' 'oil'
                    'R5100'	'Solid biofuels' 'biomass'
                    'R5210P'	'Pure biogasoline' 'other_biogas'
                    'R5220P'	'Pure biodiesels' 'other_biogas'
                    'R5290'	'Other liquid biofuels' 'other_biogas'
                    'R5300'	'Biogases' 'other_biogas'
                    'W6100'	'Industrial waste (non-renewable)' 'waste'
                    'W6210'	'Renewable municipal waste' 'waste'
                    'W6220'	'Non-renewable municipal waste' 'waste'} ;